#FROM node:14-alpine
FROM node:16.19.0-slim

ARG CURRENT_UID
#RUN test -n "$CURRENT_UID"
ARG CURRENT_GID
#RUN test -n "$CURRENT_GID"

ENV CURRENT_UID=${CURRENT_UID:-1000}
#RUN test -n "$CURRENT_UID"
ENV CURRENT_GID=${CURRENT_GID:-1000}

RUN apt-get update -qq \
    && apt-get dist-upgrade --yes -qq \
    && apt-get autoremove --yes && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN groupmod -og $CURRENT_GID node && usermod -u $CURRENT_UID node

RUN usermod -d /app node

ENV NODE_PATH /opt/node_modules
#ENV NODE_OPTIONS=--openssl-legacy-provider
# used by print_versions
ENV VUE_VERSION 2.0

WORKDIR /app

COPY ./app/package.json  .

RUN yarn install

COPY ./app /app

EXPOSE 8080
EXPOSE 8081

COPY banner.sh print_versions.sh /etc/
RUN echo '/bin/bash /etc/banner.sh' >> /etc/bash.bashrc
#COPY ./docker-entrypoint.sh /usr/local/bin/docker-entrypoint
COPY ./docker-entrypoint.sh /docker-entrypoint2
RUN chmod +x /docker-entrypoint2
RUN chown node:node /docker-entrypoint2

#CMD [ "npm", "run", "serve" ]
CMD [ "tail", "-f", "/dev/null" ]
#CMD ["/docker-entrypoint"]