# FROM node:14-alpine 
#FROM node:14-alpine 
FROM node:14-alpine 

ARG CURRENT_UID
RUN test -n "$CURRENT_UID"
ARG CURRENT_GID
RUN test -n "$CURRENT_GID"

ENV NODE_PATH /opt/node_modules
ENV VUE_VERSION 15.0.4

WORKDIR /app

COPY ./app/package.json  .

#RUN npm install

COPY ./app .

#RUN  npm run build
 
#FROM nginx AS production-stage

#COPY --from=build-stage /app/dist /usr/share/nginx/html
#COPY --from=build-stage /app /app

#RUN addgroup --gid $CURRENT_GID node
RUN echo "uid= ${CURRENT_UID}"

#RUN adduser --home /app  --disabled-password --gecos ''   node

# Set the active user and open the interactive terminal
EXPOSE 8080
EXPOSE 8081

COPY banner.sh print_versions.sh /etc/
RUN echo '/bin/bash /etc/banner.sh' >> /etc/bash.bashrc

#COPY ./docker-entrypoint.sh /usr/local/bin/docker-entrypoint

COPY ./docker-entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh 

#RUN chown -R node:node /app
#RUN chmod -R 775 /app

USER node

#CMD ["/entrypoint.sh"]
CMD ["tail","-f","/dev/null"]


# CMD ["nginx", "-g", "daemon off;"]


